<?php

declare(strict_types=1);

namespace Issac\Pdf;

use Issac\Domain\EventRepository;
use Issac\Domain\InstrumentRepository;
use Issac\Domain\ResponseRepository;
use Issac\Domain\ScoringService;
use Mpdf\Mpdf;
use Mpdf\MpdfException;
use Mpdf\Output\Destination;

defined('ABSPATH') || exit;

/**
 * Builds and outputs the ISSAC assessment PDF via mPDF.
 */
final class ReportGenerator
{
    private const EVENT_KEY = 'pdf_generated';

    /**
     * Generate the PDF for an assessment.
     *
     * @param object $assessment Row from wp_issac_assessments.
     * @param string $mode       'stream' (download) or 'save' (file).
     * @return string|null       File path when $mode='save', null on stream.
     */
    public static function generate(object $assessment, string $mode = 'stream'): ?string
    {
        $tree      = InstrumentRepository::tree();
        $responses = ResponseRepository::forAssessment((int) $assessment->id);
        $summary   = ScoringService::summary($tree, $responses);
        $user      = get_userdata((int) $assessment->user_id);

        if ($user === false) {
            wp_die(
                esc_html__('Unable to generate report: user not found.', 'issac-assessment'),
                esc_html__('Report Error', 'issac-assessment'),
                ['response' => 500]
            );
        }

        ob_start();
        include __DIR__ . '/templates/report.php';
        $html = ob_get_clean();

        if ($html === false) {
            wp_die(
                esc_html__('Unable to generate report: template rendering failed.', 'issac-assessment'),
                esc_html__('Report Error', 'issac-assessment'),
                ['response' => 500]
            );
        }

        $tempDir = self::ensureTempDir();
        $filename = 'ISSAC-Report-' . gmdate('Y-m-d') . '.pdf';

        try {
            $mpdf = new Mpdf([
                'mode'          => 'utf-8',
                'format'        => 'A4',
                'margin_left'   => 15,
                'margin_right'  => 15,
                'margin_top'    => 20,
                'margin_bottom' => 20,
                'tempDir'       => $tempDir,
                'default_font'  => 'dejavusans',
            ]);

            $mpdf->SetFooter('Generated by ISSAC Assessment Platform · {DATE j F Y}');
            $mpdf->WriteHTML($html);

            EventRepository::recordOrTouch((int) $assessment->id, self::EVENT_KEY);

            if ($mode === 'save') {
                $saveDir = self::ensureSaveDir((int) $assessment->user_id);
                $path    = $saveDir . '/' . $filename;
                $mpdf->Output($path, Destination::FILE);

                return $path;
            }

            while (ob_get_level()) {
                ob_end_clean();
            }

            $mpdf->Output($filename, Destination::DOWNLOAD);

            return null;
        } catch (MpdfException $e) {
            wp_die(
                esc_html__('Unable to generate report. Please try again later.', 'issac-assessment'),
                esc_html__('Report Error', 'issac-assessment'),
                ['response' => 500]
            );
        }
    }

    private static function uploadsBaseDir(): string
    {
        $uploadDir = wp_upload_dir();

        return rtrim($uploadDir['basedir'], '/\\');
    }

    private static function ensureProtectedDir(string $path): string
    {
        if (!is_dir($path)) {
            wp_mkdir_p($path);
        }

        $indexFile = $path . '/index.php';
        if (!file_exists($indexFile)) {
            file_put_contents($indexFile, "<?php // Silence is golden.\n");
        }

        $htaccessFile = $path . '/.htaccess';
        if (!file_exists($htaccessFile)) {
            file_put_contents($htaccessFile, "Deny from all\n");
        }

        return $path;
    }

    private static function ensureTempDir(): string
    {
        return self::ensureProtectedDir(self::uploadsBaseDir() . '/issac-tmp');
    }

    private static function ensureSaveDir(int $userId): string
    {
        return self::ensureProtectedDir(self::uploadsBaseDir() . '/issac-reports/' . absint($userId));
    }
}
